---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Add "/etc/ansible/hosts"
      blockinfile: 
        path: /etc/ansible/hosts
        block: |
          [PrimaryMaster]
          192.168.0.10
          [SecondaryMaster]
          192.168.0.11
          192.168.0.12
          [Masters]
          192.168.0.10
          192.168.0.11
          192.168.0.12
          [Workers]
          192.168.0.20
          192.168.0.30
          [Storage]
          192.168.0.40
          [PrimaryLB]
          192.168.0.122
          [SecondaryLB]
          192.168.0.123
          [LBs]
          192.168.0.122
          192.168.0.123 
        
          [All]
          192.168.0.10
          192.168.0.11
          192.168.0.12
          192.168.0.20
          192.168.0.30
          192.168.0.40
          192.168.0.122
          192.168.0.123
