---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Add "/etc/hosts"
      blockinfile: 
        path: /etc/hosts
        block: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          192.168.0.10 controller1.example.com controller1
          192.168.0.11 controller2.example.com controller2
          192.168.0.12 controller3.example.com controller3
          192.168.0.20 worker1.example.com worker1
          192.168.0.30 worker2.example.com worker2
          192.168.0.40 storage.example.com storage
          192.168.0.200 lb.example.com
    - name: Add "/etc/ansible/hosts"
      blockinfile: 
        path: /etc/ansible/hosts
        block: |
          [PrimaryMaster]
          192.168.0.10
          [SecondaryMaster]
          192.168.0.11
          192.168.0.12
          [Masters]
          controller1.example.com ansible_agent=192.168.0.10
          controller2.example.com ansible_agent=192.168.0.11
          controller3.example.com ansible_agent=192.168.0.13
          [Workers]
          192.168.0.20
          192.168.0.30
          [Storage]
          192.168.0.40
          [PrimaryLB]
          192.168.0.122
          [SecondaryLB]
          192.168.0.123
          [LBs]
          192.168.0.122
          192.168.0.123 
          [VIP]
          192.168.0.200
          [All]
          192.168.0.10
          192.168.0.11
          192.168.0.12
          192.168.0.20
          192.168.0.30
          192.168.0.40
          192.168.0.122
          192.168.0.123
