---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Add "/etc/ansible/hosts"
      blockinfile: 
        path: /etc/ansible/hosts
        block: |
          [Controller]
          192.168.0.10
          192.168.0.11
          192.168.0.12
          [Workers]
          192.168.0.20
          192.168.0.30
          [Storage]
          192.168.0.40
