---
- name: Undo changes on LBs (Load Balancers)
  hosts: LBs
  become: yes
  gather_facts: yes  # 시스템 정보 수집
  tasks:
    - name: Disable HAProxy service
      systemd:
        name: haproxy
        state: stopped
        enabled: no  # HAProxy 서비스를 비활성화
      when: "'haproxy' in ansible_facts.services"  # 서비스가 존재하는 경우에만 실행
      
    - name: Uninstall HAProxy
      dnf:
        name: haproxy
        state: absent  # HAProxy 패키지를 제거

    - name: Remove HAProxy configuration
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent  # HAProxy 설정 파일 삭제


- name: Undo changes on PrimaryLB
  hosts: PrimaryLB
  become: yes
  tasks:
    - name: Uninstall Keepalived
      dnf:
        name: keepalived
        state: absent  # Keepalived 패키지를 제거

    - name: Remove Keepalived configuration
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent  # Keepalived 설정 파일 삭제

    - name: Disable Keepalived service
      systemd:
        name: keepalived
        state: stopped
        enabled: no  # Keepalived 서비스를 비활성화

- name: Undo changes on SecondaryLB
  hosts: SecondaryLB
  become: yes
  tasks:
    - name: Uninstall Keepalived
      dnf:
        name: keepalived
        state: absent  # Keepalived 패키지를 제거

    - name: Remove Keepalived configuration
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent  # Keepalived 설정 파일 삭제

    - name: Disable Keepalived service
      systemd:
        name: keepalived
        state: stopped
        enabled: no  # Keepalived 서비스를 비활성화

- name: Revert the servers
  hosts: LBs  # 모든 호스트에 대해 작업 수행
  become: yes  # root 권한으로 실행
  tasks:
    - name: Reboot the system
      reboot:
        reboot_timeout: 600  # 재부팅 최대 대기 시간 (초)
        test_command: uptime  # 재부팅 후 실행할 명령어 (시스템이 응답하면 종료)
