---
- name: Reset Kubernetes and remove related packages
  hosts: 
    - Controller  # controller 호스트 그룹
    - Workers     # worker 호스트 그룹
  gather_facts: no
  serial: 1  # 하나씩 순차적으로 실행

  tasks:
    - name: Reset kubeadm configuration
      shell: kubeadm reset --force
      become: yes
      become_user: root  # 루트 권한으로 실행
      ignore_errors: yes  # 실패해도 무시하고 계속 진행

    - name: Remove cri-o, kubelet, kubeadm, and kubectl
      dnf:
        name:
          - cri-o
          - kubelet
          - kubeadm
          - kubectl
        state: absent
      become: yes
      become_user: root  # 루트 권한으로 실행

    - name: Reboot the system
      reboot:
        reboot_timeout: 600  # 재부팅 최대 시간 (초)
      become: yes
      become_user: root  # 루트 권한으로 실행
