
---
- name: Configure Kubernetes Controller
  hosts: Controller  # controller 호스트 그룹
  gather_facts: no

  tasks:
    - name: Run 01-node-configure.sh
      shell: sh /ansible/kosa-infra-lab/01-node-configure.sh
      become: yes
      become_user: root  # 루트 권한으로 실행

    - name: Run 02-kubeadm-controller.sh
      shell: sh /ansible/kosa-infra-lab/02-kubeadm-controller.sh
      become: yes
      become_user: root  # 루트 권한으로 실행

    - name: Run 04-helm-controller.sh
      shell: sh /ansible/kosa-infra-lab/04-helm-controller.sh
      become: yes
      become_user: root  # 루트 권한으로 실행

    - name: Export KUBECONFIG environment variable
      shell: export KUBECONFIG=/etc/kubernetes/admin.conf
      become: yes
      become_user: root

    - name: Run 05-calico-installation.sh
      shell: sh /ansible/kosa-infra-lab/05-calico-installation.sh
      become: yes
      become_user: root  # 루트 권한으로 실행

- name: Configure Kubernetes Worker Nodes
  hosts: Worker  # worker 호스트 그룹
  gather_facts: no
  serial: 1  # 하나씩 순차적으로 실행

  tasks:
    - name: Run 01-node-configure.sh
      shell: sh /ansible/kosa-infra-lab/01-node-configure.sh
      become: yes
      become_user: root  # 루트 권한으로 실행

    - name: Run 03-kubeadm-join.sh
      shell: sh /ansible/kosa-infra-lab/03-kubeadm-join.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
