- name: Configure Kubernetes PrimaryMaster
  hosts: PrimaryMaster  # PrimaryMaster 호스트 그룹
  gather_facts: no

  tasks:
    - name: Install Git
      package:
        name: git
        state: present
      become: yes

    - name: Clone kosa-infra-lab repository
      git:
        repo: "https://github.com/hyukjinKimm/kosa-infra-lab.git"
        dest: "/kosa-infra-lab"
        force: yes  # 기존 디렉토리 삭제 후 다시 클론
      become: yes

    - name: Run 01-node-configure.sh
      shell: sh 01-node-configure.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
      args:
        chdir: /kosa-infra-lab  # 해당 디렉토리에서 실행

    - name: Run 02-kubeadm-controller.sh
      shell: sh 02-kubeadm-controller.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
      args:
        chdir: /kosa-infra-lab  # 해당 디렉토리에서 실행
      register: kubeadm_controller_output

    - name: Save all output to file
      copy:
        content: "{{ kubeadm_controller_output.stdout }}"
        dest: "/kosa-infra-lab/kubeadm_controller_output.log"
      become: yes
      become_user: root

    - name: Generate master_join.sh
      raw: |
        bash -c 'echo "#! /bin/bash" > /kosa-infra-lab/master_join.sh;
             sed -n '72,74p' /kosa-infra-lab/kubeadm_controller_output.log >> /kosa-infra-lab/master_join.sh'

    - name: Generate worker_join.sh
      raw: |
        bash -c 'echo "#! /bin/bash" > /kosa-infra-lab/worker_join.sh;
             sed -n '82,83p' /kosa-infra-lab/kubeadm_controller_output.log >> /kosa-infra-lab/worker_join.sh'

    - name: Wait for Kubernetes API server to be ready
      wait_for:
        host: "192.168.100.101"
        port: 6443
        delay: 10
        timeout: 900
      become: yes
      become_user: root

    - name: Run 04-helm-controller.sh
      shell: sh 04-helm-controller.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
      args:
        chdir: /kosa-infra-lab  # 해당 디렉토리에서 실행

    - name: Run 05-flannel-installation.sh
      shell: sh 05-flannel-installation.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
      args:
        chdir: /kosa-infra-lab  # 해당 디렉토리에서 실행

    - name: master_join move to control node
      fetch:
        src: /kosa-infra-lab/master_join.sh
        dest: /root/master_join.sh
        flat: yes

    - name: worker_join move to control node
      fetch:
        src: /kosa-infra-lab/worker_join.sh
        dest: /root/worker_join.sh
        flat: yes

