- name: Configure Kubernetes SecondaryMaster
  hosts: SecondaryMaster
  gather_facts: no
  serial: 1  # 한 번에 하나의 노드만 실행
  
  tasks:
    - name: Copy master_join.sh to SemiMaster
      copy:
        src: /root/master_join.sh  
        dest: /root/master_join.sh           

    - name: Install Git
      package:
        name: git
        state: present
      become: yes

    - name: Clone kosa-infra-lab repository
      git:
        repo: "https://github.com/hyukjinKimm/kosa-infra-lab.git"
        dest: "/kosa-infra-lab"
        force: yes  # 기존 디렉토리 삭제 후 다시 클론
      become: yes

    - name: Run 01-node-configure.sh
      shell: sh 01-node-configure.sh
      become: yes
      become_user: root  # 루트 권한으로 실행
      args:
        chdir: /kosa-infra-lab  # 해당 디렉토리에서 실행

    - name: Join SemiMaster
      shell: sh /root/master_join.sh 
      become: yes
      become_user: root  # 루트 권한으로 실행


